name: conda-test

on: [push]

jobs:
  conda-cache:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    continue-on-error: true
    outputs:
      pytestOutput: ${{ steps.unit-tests.outputs.test }}
      mypyOutput: ${{ steps.type-checks.outputs.test }}
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          activate-environment: bag_py3d7_c
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: check env
        run: echo "CONDA=$CONDA"
      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('conda_test.yml') }}-${{
            env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: 0
        id: cache
      - name: Update environment
        run: |
          echo "CONDA=$CONDA"
          conda env update -n bag_py3d7_c -f conda_test.yml
        if: steps.cache.outputs.cache-hit != 'true'
  conda-cache-load:
    needs: conda-cache
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    continue-on-error: true
    outputs:
      pytestOutput: ${{ steps.unit-tests.outputs.test }}
      mypyOutput: ${{ steps.type-checks.outputs.test }}
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          activate-environment: bag_py3d7_c
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('conda_test.yml') }}-${{
            env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: 0
        id: cache
