name: pybag-pr-ci

on: [push]

env:
  POETRY_VERSION: "1.2.0"

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      pytestOutput: ${{ steps.unit-tests.outputs.test }}
      mypyOutput: ${{ steps.type-checks.outputs.test }}
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          activate-environment: bag_py3d7_c
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          auto-activate-base: false
      - name: Cache Conda env
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('environment.yml') }}-${{
            env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run:
          conda env update -n bag_py3d7_c -f
          environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      # - name: Load Cached Poetry Install
      #   id: cached-poetry
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.local
      #     key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}
      # - name: Install Poetry
      #   uses: snok/install-poetry@v1
      #   if: steps.cached-poetry.outputs.cache-hit != 'true'
      #   with:
      #     virtualenvs-create: true
      #     virtualenvs-in-project: true
      #     version: ${{ env.POETRY_VERSION }}
      # - name: Load Cached Poetry virtualenv
      #   id: cached-venv
      #   uses: actions/cache@v3
      #   with:
      #     path: .venv
      #     key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
      # - name: Create Poetry env
      #   if: steps.cached-venv.outputs.cache-hit != 'true'
      #   run: |
      #     poetry config virtualenvs.in-project true
      #     poetry install --no-ansi
      # - name: Run unit tests
      #   id: unit-tests
      #   run: |
      #     poetry run pytest tests/ -v
      - name: Run unit tests
        id: unit-tests
        run: |
          pytest tests/ -v
      # - name: Type checking
      #   id: type-checks
      #   run: |
      #     touch .venv/lib/python${{ matrix.python-version }}/site-packages/ruamel/py.typed
      #     touch .venv/lib/python${{ matrix.python-version }}/site-packages/networkx/py.typed
      #     poetry run pyright